POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Mary Poppendieck",
    "number": "+351 964 265 111"
}

###
GET http://localhost:3001/api/persons HTTP/1.1
Content-Type: 'application/json'
